### ISSUE TITLE
batch import of treebanks to web interface

### ISSUE THREAD

**Issue by matyaskopp** [ufal/tred-extension-pmltq#2]
- create a new command to pmltq - _loadweb_
- add new settings to yaml config file:

``` yaml

---
data_dir: /pmltq/data/dir/ # directory where the data are (this is also base directory for data layers)
resources: /pmltq/resources/ # main directory with PML schemas

db: # typical DB auth stuff
  name: treebank_db_name
  host: localhost
  port: 5432
  user: pmltq
  password: pwd

title: "pdt20"
treebank_id: pdt20
homepage: "http://..." ##
description: "description of treebank - visible on web" ##
public: 1 ##
free: 1 ##
featured: 0 ##
manuals:
   -
tags:
  - pdt
languages:
  - en ## language abbrevitation
server: euler

layers:
  - name: adata
    data: ./relative/to/data_dir/**/*.a.gz
    path: data/pdt/pdt20 # relative path to data on pmltq server (access is needed to generate trees and to be able make queries from tred)
    resources:
      - extra_resource
    references:
      - [ t-node/val_frame.rf ] # equals to t-node/val_frame.rf=-
      - [ t-a/aux.rf, "adata:a-node" ] # t-a/aux.rf=adata:a-node
      - [ t-node/coref_gram.rf, a-node ] # t-node/coref_gram.rf=t-node
  - name: tdata
    data: **/*.t.gz
  - name: vallency_lexicon
    data: ./valex_pml
```
## not clear to me:
- how compare language/tag/server?
- what to do if  language/tag/server does not match with records on pmltq web server?
- should this command contains synchronization of data files with euler?
